//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public string DeptID { get; set; }
        public string DeptName { get; set; }
        public string DivID { get; set; }
        public string DeptRemarks { get; set; }
        public string DeptHead { get; set; }
    }
}
