//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsOfRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailsOfRequest()
        {
            this.RequestHistories = new HashSet<RequestHistory>();
        }
    
        public int Request_ID { get; set; }
        public string Emp_ID { get; set; }
        public System.DateTime DateCreated { get; set; } = DateTime.Now;
        public string Channel { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string CoveragePeriod { get; set; }
        public string GamePlan { get; set; }
        public string SupportingDocuments { get; set; }
        public string Objectives { get; set; }
        public string Mechanics { get; set; }
        public string ResourcesNeeded { get; set; }
        public string Amount { get; set; }
        public string CostToSales { get; set; }
        public string AllocatedAnnualBudget { get; set; }
        public string YTDExpenses { get; set; }
        public string RemainingBudget { get; set; }
        public System.DateTime DateNeeded { get; set; } = DateTime.Now;
        public string Status { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestHistory> RequestHistories { get; set; }
    }
}
