//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginRequest
    {
        public int Id { get; set; }
        public string Emp_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
